# Generated by Django 5.1.7 on 2025-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_course_enrollment_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="video_url",
        ),
        migrations.AddField(
            model_name="video",
            name="video_file",
            field=models.FileField(default="videos/default.mp4", upload_to="videos/"),
        ),
    ]
