pipeline {
    agent any

    environment {
        IMAGE_NAME = "stockfocus:v2.0"
        CONTAINER_NAME = "stockfocus_container"
    }

    stages {
        stage('Pull Code') {
            steps {
                sh 'git pull origin main'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                    docker stop $CONTAINER_NAME || true
                    docker rm $CONTAINER_NAME || true
                    docker run -d -p 8000:8000 --name $CONTAINER_NAME $IMAGE_NAME
                '''
            }
        }
    }
}
